services:
  api:
    ports: !reset []

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped

    depends_on:
      api:
        condition: service_healthy

    environment:
      API_DOMAIN: ${API_DOMAIN}

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config

    networks:
      - interne

volumes:
  caddy-data:
  caddy-config:
