spring.datasource.url=jdbc:postgresql://localhost:5434/campustasks_db
spring.datasource.username=campustasks_user
spring.datasource.password=campustasks_pass

application.securite.jwt.secret=cle-de-developpement-uniquement-ne-jamais-utiliser-en-production
