spring.application.name=campus-tasks-api
server.port=${PORT:8080}

spring.devtools.restart.enabled=false

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.open-in-view=false

application.securite.jwt.secret=${JWT_SECRET}
application.securite.jwt.acces-validite-ms=900000
application.securite.jwt.rafraichissement-validite-ms=604800000

application.cors.origines=${CORS_ORIGINES:http://localhost:3000,http://localhost:4200,http://localhost:8080,http://10.0.2.2:8080}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

logging.level.root=INFO
logging.level.iibs.campustasks=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=INFO

logging.pattern.console=%d{HH:mm:ss.SSS} %-5level [%logger{36}] - %msg%n

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

spring.jackson.default-property-inclusion=non_null
